In [3]:
import os
import numpy as np

data_path=r'C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2'

labels=os.listdir(data_path)
categories=np.arange(len(labels))
categori_dict=dict(zip(labels,categories))
print(categori_dict)

{'Barack Obama': np.int64(0), 'Donald Trump': np.int64(1), 'George W Bush': np.int64(2)}


In [5]:
# import cv2


# for label in labels:
#     imgs_path=os.path.join(data_path,label)
#     # print(imgs_path)
#     img_names=os.listdir(imgs_path)
#     # print(img_names)
#     # print('---------------------------------')
#     for img_name in img_names:
#         img_path=os.path.join(imgs_path,img_name)
#         print(img_path)
#         img=cv2.imread(img_path)
#         cv2.imshow('img',img)
#         k=cv2.waitKey(100)
#         if(k==27):
#             break
# cv2.destrayAllWindows()

In [17]:
# import cv2
# face_classifier=cv2.CascadeClassifier(r"C:\Users\hp\Desktop\New folder\ML\part4_facere\haarcascade_frontalface_default.xml")

# for label in labels:
#     imgs_path=os.path.join(data_path,label)
#     # print(imgs_path)
#     img_names=os.listdir(imgs_path)
#     # print(img_names)
#     # print('---------------------------------')
#     for img_name in img_names:
#         img_path=os.path.join(imgs_path,img_name)
#         print(img_path)
#         img=cv2.imread(img_path)
#         gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
#         faces=face_classifier.detectMultiScale(gray)

#         for(x,y,w,h) in faces:
#             # cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
#             cropped_face=gray[y:y+h,x:x+w]
        
#         # cv2.imshow('img',img)
#         cv2.imshow('img',cropped_face)
#         # k=cv2.waitKey(100)
#         if(k==27):
#             break
# cv2.destroyAllWindows()

C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][10211].jpg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][106]obama-women-leaders_wide-9abe491af119581d41fcfc752e421c934e4afafd.jpg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][107]16virus-obama-swap-superJumbo-v2.jpg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][10]barack_obama001.jpg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][113]BarackObama2005portrait.jpg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][11687].jpg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][120]barack-obama.jpeg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][13575].jpg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_da

In [ ]:
import cv2
face_classifier=cv2.CascadeClassifier(r"C:\Users\hp\Desktop\New folder\ML\part4_facere\haarcascade_frontalface_default.xml")

data=[]
target=[]

for label in labels:
    imgs_path=os.path.join(data_path,label)
    # print(imgs_path)
    img_names=os.listdir(imgs_path)
    # print(img_names)
    # print('---------------------------------')
    for img_name in img_names:
        img_path=os.path.join(imgs_path,img_name)
        print(img_path)
        img=cv2.imread(img_path)
        gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
        faces=face_classifier.detectMultiScale(gray)

        for(x,y,w,h) in faces:
            # cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
            cropped_face=gray[y:y+h,x:x+w]
            cv2.imshow('cropped_face',cropped_face)
            print('right')
            k=cv2.waitKey(0)
            if(k==121):
                cropped_face=cv2.resize(cropped_face,(50,50))
                data.append(cropped_face)
                target.append(categori_dict[label])
            
        
        # # cv2.imshow('img',img)
        # cv2.imshow('img',cropped_face)
        # # k=cv2.waitKey(100)
        # if(k==27):
        #     break
cv2.destroyAllWindows()

C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][10211].jpg
right
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][106]obama-women-leaders_wide-9abe491af119581d41fcfc752e421c934e4afafd.jpg
right
right
right
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][107]16virus-obama-swap-superJumbo-v2.jpg
right
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][10]barack_obama001.jpg
right
right
right
right
right
right
right
right
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][113]BarackObama2005portrait.jpg
right
right
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][11687].jpg
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\Barack Obama\[www.google.com][120]barack-obama.jpeg
right
C:\Users\hp\Desktop\New folder\ML\part4_facere\train_data_2\

In [ ]:
data=np.array(data)
data=data.reshape(data.shape[0],data.shape[1]*data.shape[2])
target=np.array(target)

np.save('data',data)
np.save('target',target)

##data tika api hadagattha etika save karanawa

In [1]:
import numpy as np
data=np.load(r"C:\Users\hp\Desktop\New folder\ML\part4_facere\data.npy")
target=np.load(r"C:\Users\hp\Desktop\New folder\ML\part4_facere\target.npy")

In [3]:
print(data.shape)
print(target.shape)

(285, 2500)
(285,)


In [5]:
import collections
print(collections.Counter(target))

Counter({np.int32(1): 113, np.int32(2): 91, np.int32(0): 81})


In [7]:
from sklearn.svm import SVC #importing the SVM
from sklearn.decomposition import PCA #importing PCA
from sklearn.pipeline import make_pipeline

pca=PCA(n_components=150,whiten=True,random_state=42)
svc=SVC(kernel='rbf')

model=make_pipeline(pca,svc)

In [9]:
from sklearn.model_selection import train_test_split

train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [11]:
model.fit(train_data,train_target)

Pipeline(steps=[('pca', PCA(n_components=150, random_state=42, whiten=True)),
                ('svc', SVC())])

In [13]:
predicted_target=model.predict(test_data)

In [15]:
from sklearn.metrics import accuracy_score

acc=accuracy_score(test_target,predicted_target)
print(acc)

0.896551724137931


In [17]:
from sklearn.metrics import classification_report

print(classification_report(test_target,predicted_target,target_names=['Barack Obama', 'Donald Trump', 'George W Bush']))

               precision    recall  f1-score   support

 Barack Obama       1.00      0.78      0.88         9
 Donald Trump       1.00      0.93      0.96        14
George W Bush       0.67      1.00      0.80         6

     accuracy                           0.90        29
    macro avg       0.89      0.90      0.88        29
 weighted avg       0.93      0.90      0.90        29



In [ ]:
##meka 1ta lan wenna lan wenna hodai okkoma 

In [19]:
from sklearn.metrics import confusion_matrix

matrix=confusion_matrix(test_target,predicted_target)
print(matrix)

[[ 7  0  2]
 [ 0 13  1]
 [ 0  0  6]]


In [21]:
import joblib

joblib.dump(model,'SVM-Face Recognition my.sav')

['SVM-Face Recognition my.sav']

In [ ]:
##comfution metrics blanna

In [31]:
import joblib

model=joblib.load(r"C:\Users\hp\Desktop\New folder\ML\part4_facere\SVM-Face Recognition my.sav")

In [39]:
category_dict={0:'Barack Obama', 1:'Donald Trump',2:'George W Bush'}

In [1]:
test_data_path=r"C:\Users\hp\Desktop\New folder\ML\part4_facere\test_data"

import os
import cv2

face_classifier=cv2.CascadeClassifier(r"C:\Users\hp\Desktop\New folder\ML\part4_facere\haarcascade_frontalface_default.xml")

test_img_names=os.listdir(test_data_path)
print(test_img_names)

for test_img in test_img_names:
    img_path=os.path.join(test_data_path,test_img)
    test_img=cv2.imread(img_path)
    
    gray=cv2.cvtColor(test_img,cv2.COLOR_BGR2GRAY)
    
    faces=face_classifier.detectMultiScale(gray)
    
    for (x,y,w,h) in faces:
        
        cv2.rectangle(test_img,(x,y),(x+w,y+h),(0,255,0),2)
        
        cropped_face=gray[y:y+h,x:x+w]
        cropped_face=cv2.resize(cropped_face,(50, 50))
        cropped_original=cropped_face
        cropped_face=cropped_face.reshape(1,50*50)
        
        result=model.predict(cropped_face)
        name=category_dict[result[0]]

        cv2.putText(test_img,name,(x,y-10),cv2.FONT_HERSHEY_SIMPLEX,1.5,(0,255,0),2)
        cv2.imshow('GRAY',cropped_original)
    cv2.imshow('LIVE',test_img)
    
    
    k=cv2.waitKey(1000)
    if(k==27):
        break
cv2.destroyAllWindows()

['barack-obama-12782369-1-402.jpg', 'barack-obama.jpeg', 'https___d1e00ek4ebabms.cloudfront.net_production_b8c5ac6e-d1ec-467a-b185-a5c7b2fc1c9b.jpg', 'president-george-w-bush-listens-to-a-question-during-a-news-news-photo-1591807580.jpg', 'screen_shot_2020-06-07_at_9.28.05_am.png', 'trump.jpg']


NameError: name 'model' is not defined